language: python
dist: xenial
cache: pip
python:
  - 3.6
  - 3.7
stages:
  - deploy
before_script:
  - pip3 install -U poetry
jobs:
  include:
    - stage: deploy
      python: 3.7
      script: skip
      before_install:
        - pip3 install poetry
      install:
        - poetry install
      before_deploy:
        - poetry build
      deploy:
        provider: script
        script: poetry publish -u $PYPI_USER -p $PYPI_PASS
        skip_cleanup: true
#        on:
#          tags: true
